#!/usr/bin/env node

var config = JSON.parse(fs.readFileSync(__dirname + '/../../config.json', 'utf8'))

var fs = require('fs')
var sp = require("serialport");
/*
sp.list(function (err, ports) {
  ports.forEach(function(port) {
    console.log(port.comName);
    console.log(port.pnpId);
    console.log(port.manufacturer);
  });
});
*/

var SerialPort = require("serialport").SerialPort
var serialPort = new SerialPort(config.simpleserial.serialPortLocation, {
  baudrate: config.simpleserial.baudrate
});

serialPort.on("open", function () {
  var string = ''
  var delimetersSeen = 0
  serialPort.on('data', function(data) {
    data = String(data)
    if (data.indexOf('x') == -1) {
      string += data 
    }
    else {
      delimetersSeen++
      string += data.substr(0, data.indexOf('x'))
      string = string.trim()
      dataPoint = parseFloat(string)
      var scale = 1000.00
      var airMax = .1
      var resolution = 1024.00
      dataPoint = (dataPoint / resolution) * airMax * scale
      if (delimetersSeen >= 2) {
        console.log(dataPoint)
        process.exit()
      }
      string = data.substr(data.indexOf('x')+1, data.length)
    }
  });
});

